######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 30 23:44:18 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gridcell.h gridwindow.h
SOURCES += gridcell.cpp gridwindow.cpp main.cpp
