######################################################################
# Automatically generated by qmake (2.01a) Tue May 1 16:51:06 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += cell.h gridcell.h gridwindow.h world.h
SOURCES += cell.cpp gridcell.cpp gridwindow.cpp main.cpp world.cpp
